# Generated by Django 5.1.1 on 2024-10-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_remove_post_price_remove_post_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='News',
        ),
    ]
