# Generated by Django 5.1.1 on 2024-10-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0007_remove_news_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('новость', 'Новость'), ('статья', 'Статья')], default='новость', max_length=7),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
