# Generated by Django 5.1.1 on 2024-10-05 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_rename_post_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default='Содержание статьи будет добавлено позже.'),
        ),
        migrations.AddField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Заголовок будет добавлен позже.', max_length=200),
        ),
    ]
