# Generated by Django 5.1.1 on 2024-10-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0005_remove_news_description_remove_news_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='name',
            field=models.CharField(default='статья', max_length=50, unique=True),
        ),
    ]
